-- 创建违禁词表
CREATE TABLE IF NOT EXISTS banned_words (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    word VARCHAR(255) NOT NULL UNIQUE COMMENT '违禁词',
    category VARCHAR(50) COMMENT '分类：政治, 暴力, 色情, 广告, 其他',
    severity VARCHAR(20) DEFAULT 'MEDIUM' COMMENT '严重级别：LOW, MEDIUM, HIGH',
    is_active BOOLEAN DEFAULT TRUE COMMENT '是否启用',
    remark VARCHAR(500) COMMENT '备注',
    created_by BIGINT COMMENT '创建人ID',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_by BIGINT COMMENT '修改人ID',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    KEY idx_word (word),
    KEY idx_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='违禁词库表';

-- 初始化违禁词
INSERT INTO banned_words (word, category, severity, is_active, remark) VALUES
-- 政治敏感词
('法轮功', '政治', 'HIGH', TRUE, '政治敏感词'),
('藏独', '政治', 'HIGH', TRUE, '政治敏感词'),
('疆独', '政治', 'HIGH', TRUE, '政治敏感词'),
('港独', '政治', 'HIGH', TRUE, '政治敏感词'),
('台独', '政治', 'HIGH', TRUE, '政治敏感词'),
('分裂', '政治', 'MEDIUM', TRUE, '政治敏感词'),
('新疆独立', '政治', 'HIGH', TRUE, '政治敏感词'),
('西藏独立', '政治', 'HIGH', TRUE, '政治敏感词'),
('颜色革命', '政治', 'HIGH', TRUE, '政治敏感词'),
-- 不雅词汇
('傻逼', '不雅', 'MEDIUM', TRUE, '不雅词汇'),
('操你', '不雅', 'MEDIUM', TRUE, '不雅词汇'),
('垃圾', '不雅', 'LOW', TRUE, '不雅词汇'),
('草泥马', '不雅', 'MEDIUM', TRUE, '不雅词汇'),
('滚蛋', '不雅', 'LOW', TRUE, '不雅词汇'),
('废物', '不雅', 'LOW', TRUE, '不雅词汇'),
('混蛋', '不雅', 'MEDIUM', TRUE, '不雅词汇'),
('你妈', '不雅', 'MEDIUM', TRUE, '不雅词汇'),
('去死', '不雅', 'MEDIUM', TRUE, '不雅词汇'),
('该死', '不雅', 'LOW', TRUE, '不雅词汇'),
-- 诈骗词汇
('裸贷', '诈骗', 'HIGH', TRUE, '诈骗词汇'),
('刷单', '诈骗', 'HIGH', TRUE, '诈骗词汇'),
('代办证件', '违法', 'HIGH', TRUE, '违法词汇'),
('兼职刷单', '诈骗', 'HIGH', TRUE, '诈骗词汇'),
('刷信誉', '诈骗', 'HIGH', TRUE, '诈骗词汇'),
('点赞赚钱', '诈骗', 'MEDIUM', TRUE, '诈骗词汇'),
('转发赚钱', '诈骗', 'MEDIUM', TRUE, '诈骗词汇'),
('充值返利', '诈骗', 'HIGH', TRUE, '诈骗词汇'),
('投资理财', '诈骗', 'MEDIUM', TRUE, '诈骗词汇'),
('虚拟币', '诈骗', 'MEDIUM', TRUE, '诈骗词汇'),
('挖矿', '诈骗', 'MEDIUM', TRUE, '诈骗词汇'),
('期货', '诈骗', 'MEDIUM', TRUE, '诈骗词汇'),
('外汇', '诈骗', 'MEDIUM', TRUE, '诈骗词汇'),
-- 暴力相关
('暴力', '暴力', 'MEDIUM', TRUE, '暴力相关'),
('自杀', '暴力', 'HIGH', TRUE, '自伤相关'),
('杀人', '暴力', 'HIGH', TRUE, '暴力相关'),
('砍人', '暴力', 'HIGH', TRUE, '暴力相关'),
('打死', '暴力', 'MEDIUM', TRUE, '暴力相关'),
('挨刀', '暴力', 'MEDIUM', TRUE, '暴力相关'),
('割腕', '暴力', 'HIGH', TRUE, '自伤相关'),
-- 色情词汇
('成人网站', '色情', 'HIGH', TRUE, '色情词汇'),
('福利姬', '色情', 'MEDIUM', TRUE, '色情词汇'),
('援交', '色情', 'HIGH', TRUE, '色情词汇'),
('陪睡', '色情', 'HIGH', TRUE, '色情词汇'),
('性交', '色情', 'MEDIUM', TRUE, '色情词汇'),
('操逼', '色情', 'HIGH', TRUE, '色情词汇'),
('舔', '色情', 'MEDIUM', TRUE, '色情词汇'),
('鸡', '色情', 'MEDIUM', TRUE, '色情词汇'),
-- 赌博词汇
('赌博', '赌博', 'HIGH', TRUE, '赌博相关'),
('赌钱', '赌博', 'HIGH', TRUE, '赌博相关'),
('彩票', '赌博', 'MEDIUM', TRUE, '赌博相关'),
('博彩', '赌博', 'MEDIUM', TRUE, '赌博相关'),
('老虎机', '赌博', 'HIGH', TRUE, '赌博相关'),
('麻将', '赌博', 'MEDIUM', TRUE, '赌博相关'),
('斗地主赌钱', '赌博', 'HIGH', TRUE, '赌博相关'),
('棋牌赌', '赌博', 'HIGH', TRUE, '赌博相关'),
-- 毒品词汇
('吸毒', '毒品', 'HIGH', TRUE, '毒品相关'),
('海洛因', '毒品', 'HIGH', TRUE, '毒品相关'),
('冰毒', '毒品', 'HIGH', TRUE, '毒品相关'),
('大麻', '毒品', 'HIGH', TRUE, '毒品相关'),
('摇头丸', '毒品', 'HIGH', TRUE, '毒品相关'),
('K粉', '毒品', 'HIGH', TRUE, '毒品相关'),
('白粉', '毒品', 'HIGH', TRUE, '毒品相关'),
('开毒', '毒品', 'HIGH', TRUE, '毒品相关'),
-- 广告推销
('代购', '广告', 'LOW', TRUE, '广告推销'),
('微商', '广告', 'LOW', TRUE, '广告推销'),
('淘宝店', '广告', 'LOW', TRUE, '广告推销'),
('私聊了解', '广告', 'LOW', TRUE, '广告推销'),
('扫码关注', '广告', 'LOW', TRUE, '广告推销'),
('加我微信', '广告', 'LOW', TRUE, '广告推销'),
('联系方式', '广告', 'LOW', TRUE, '广告推销'),
('v信', '广告', 'LOW', TRUE, '广告推销'),
('qq群', '广告', 'LOW', TRUE, '广告推销'),
('抖音号', '广告', 'LOW', TRUE, '广告推销'),
('快手号', '广告', 'LOW', TRUE, '广告推销'),
-- 人身攻击
('智障', '人身', 'MEDIUM', TRUE, '人身攻击'),
('脑残', '人身', 'MEDIUM', TRUE, '人身攻击'),
('滚', '人身', 'LOW', TRUE, '人身攻击'),
('滚出去', '人身', 'MEDIUM', TRUE, '人身攻击'),
('别BB', '人身', 'LOW', TRUE, '人身攻击'),
('闭嘴', '人身', 'LOW', TRUE, '人身攻击'),
('活该', '人身', 'MEDIUM', TRUE, '人身攻击'),
('死全家', '人身', 'HIGH', TRUE, '人身攻击'),
('诅咒', '人身', 'MEDIUM', TRUE, '人身攻击');
